name: Update Happ Subscription

on:
  schedule:
    - cron: '0 * * * *'  # Каждый час
  workflow_dispatch:      # Кнопка ручного запуска в Actions

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run Generator
        run: python generate.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add happ_auto.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update nodes" && git push)
